obj-$(CONFIG_GOOGLE_BMS) += google-bms.o
google-bms-objs += gbms_storage.o gvotable.o google_bms.o
obj-$(CONFIG_GOOGLE_BMS_SM7250) += sm7250_bms.o
obj-$(CONFIG_GOOGLE_CHARGER) += google_charger.o
obj-$(CONFIG_GOOGLE_BATTERY) += google-battery.o
google-battery-objs += google_battery.o google_ttf.o
obj-$(CONFIG_GOOGLE_LOGBUFFER) += logbuffer.o
